config/routes.rb
SVL::Application.routes.draw do
  resources :searches, :only => [:new, :create]
  resources :students
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/log', :to => 'pages#log'

  match '/previous_services', :to => 'pages#previous_services'

  match '/logged_in', :to => 'searches#new'

  match '/students_new', :to => 'students#new'
  match '/index', :to => 'pages#index'
  match 'students/new', :to => 'students#new'
  match '/signup',  :to => 'users#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "sessions#new"

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :lastname, :firstname, :IDnumber, :graduationyear, :grade, :address1, :address2, :zip, :email1, :email2, :confirmed1, :confirmed2, :telephone1, :telephone2

  validates :lastname, :presence => true
  validates :firstname, :presence => true
  validates :IDnumber, :presence => true

  NULL_ATTRS = %w( firstname ), %w( lastname ), %w( IDnumber ), %w( graduationyear ), %w( grade ), %w( address1 ), %w( address2 ), %w(  city ), %w( zip) , %w( email1 ), %w( email2 ), %w( confirmed1 ), %w( confirmed2 ), %w( telephone1 ), %w( telephone2 )
  before_save :nil_if_blank

  protected

  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation, :student
  validates :password_confirmation, :presence => true
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, :presence => true
  validates :email, :presence => true,
	           :format => { :with => email_regex },
                   :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true
  def has_password?(submitted_password)
    submitted_password == password
  end

  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def logo
  end

  def home
  end

  def logged_in
  end

  def previous_services
  end

  def searched
  end

  def create_student
  end

  def log
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    render 'new'
  end
  def create 
    @search = Search.create(params[:search])
    render 'searched'
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  def create
    user = User.authenticate(params[:session][:username],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid username/password combination."
      @title = "Sign in"  
      render 'new'
    else 
      sign_in user
      redirect_to logged_in_path
    end
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def create
    @student = Student.new(params[:student])
    if @student.save
      flash[:success] = "Student created successfully"
    else
      @title = "Student Creation"
      render "new"
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end
  def create
    @student = Student.new(params[:student])
    if @student.save
      flash[:success] = "Student created successfully"
      render'new'
    else
      @title = "Student Creation"
      render "new"
    end
  end
  def index
    if params[:search] 
      @student = Student.find(:all, :conditions => ["firstname like ?", "%#{params[:search]}%"])
    else 
      @student = Student.find(:all)
     
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
  end
  def logout
  end
  def create
    @suser = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the SVL!"	    
      redirect_to @user
    else
      @title = "Sign in"
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  def logout
  end
  def show
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.deliver_registration_confirmation(@user)
      flash[:success] = "Welcome to the SVL!"	    
      render :action => "new"
    else
      render "new"
    end
  end
  def new
    @user = User.new
    render "new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logo
      @logo = image_tag("logo.png", :alt => "Elrel", :class => "round")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def signed_in?
    !current_user.nil?
 end
 def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id]
    self.current_user = user
 end	
 def current_user=(user)
    @current_user = user
 end
 def current_user
   @current_user ||= user_from_remember_token
 end
 def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
 end
 def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
 end
 def current_user?(user)
    user == current_user
 end
 def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
 end
 def authenticate
    deny_access unless signed_in?
 end
 
 

 private

    def user_from_remember_token
      User.authenticate(:username, :password)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
    

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb

	<header>
	<%= link_to logo, root_path %>
	<nav>
	<% if signed_in? %>
	  <%= "You are now logged in as #{@user}" %>
        <% end %>
	<ul>
            <br>
            <li><%= link_to "Manage Account", '#' %></li>
            <li><%= link_to "Help", '#' %></li>
            <li><%= link_to "Logout", root_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SVL</title>
    <%= stylesheet_link_tag :all %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
        <section class="round">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<center><div class = "home">
<div class = "span-8">
	<center><ul>
		<%= form_tag @user, :url => logged_in_path do %>
		<li><h1><b>Login</b></h1></li>	
		<li><%= text_field_tag :username, :class => "textstyle", :placeholder => "Username" %></li>
		<li><%= password_field_tag :password, :class => "textstyle", :placeholder => "Password" %></li>
		<div class="actions">
			<li><%= submit_tag "Login"%><li>
		</div>
		<% end %>
	</ul></center>
</div>
<div class= "span-1">
	<center><img src="http://i.imgur.com/ZgEQ3.png"><center>
</div>

<div class = "span-8">
	<center><ul>
		<%= form_for @user do |f|  %>
		<li><h1><b>New Account</b></h1></li>	
		<li><%= f.text_field :email, :class => "textstyle", :placeholder => "Email" %></li>
		<li><%= f.text_field :username, :class => "textstyle", :placeholder => "New Username" %></li>
		<li><%= f.password_field :password, :class => "textstyle", :placeholder => "Password" %></li>
		<li><%= f.password_field :password_confirmation, :class => "textstyle", :placeholder => "Confirm Password" %></li>
		<div class="actions">
			<li><%= submit_tag "Create"  %><li>
		</div>
		<% end %>
	</ul></center>
</div>
</div></center>

app/views/pages/log.html.erb
<html>
	<body>
		<container class= "log">
		<div class="span-7">
				<center><ul>
					<br><br>
					<% form_tag '/upload', :multipart => true do %>
					<li><b><font size = "5">Total Service Hours</font></b><%= text_field_tag :service, "", :class => "total"%></li>
					<br><br><br>
					<li><%= link_to "", previous_services_path, :class => "viewprevious" %></li>
				</ul></center>
			</div>
			<div class= "span-2">
				<ul>
					<br>
					<li><img src="http://i.imgur.com/ZgEQ3.png"></li>
				</ul>
			</div>
			<div class = "span-10">
				<form>
					<ul>
					<br>
					<li><%= text_field_tag :dates, "", :placeholder => "Dates", :class => "loginput" %></li>
					<li><%= text_field_tag :organization, "", :placeholder => "Nonprofit Organization", :class => "loginput" %></li>
					<li><%= text_field_tag :category, "", :placeholder => "Category", :class => "loginput" %></li>
					<li><%= text_area_tag :contribution, "", :size => "1x1",:placeholder => "Contribution", :class => "loginput"%></li>
					<li><%= text_area_tag :impact, "", :placeholder => "Impact", :class => "loginput" %></li>
					<li><%= text_field_tag :hours, "", :placeholder => "Hours Volunteered", :class => "loginput" %></li>
				
					</ul>
				</form>
			</div>
			<div class = "span-2">
				<ul>
					<br>
					<li><%= link_to "Undo", logged_in_path, :class => "previous round" %></li>
					<br><br><br><br><br><br><br><br><br><br><br><br><br>
					<li><%= file_field_tag "Attach Document", :type => :image, :src => "/images/attachfilebutton.png"  %></li>
					<br>
					<li><%= link_to "Save & Refresh", logged_in_path, :class => "previous round" %></li>
				</ul>
			</div>
		<% end %>

					
		</container>
	</body>
</html>

app/views/pages/logged_in.html.erb
<div class = "students_search">
<div class = "span-8">
	<%= form_tag searched_path do %>
	<p>
	<%= text_field_tag :search, :placeholder => "First Name" %>
	<%= text_field_tag :search, :placeholder => "Last Name" %>
	<%= text_field_tag :search, :placeholder => "ID number" %>
	<%= text_field_tag :search, :placeholder => "Email" %>
	<%= text_field_tag :search, :placeholder => "Telephone" %>
	<%= submit_tag "", :type => :image, :src => "/images/SearchButton.png" %>
	</p>
	<% end %>
	</div>
	</div>

app/views/pages/previous_services.html.erb
<h1>Pages#previous_services</h1>
<p>Find me in app/views/pages/previous_services.html.erb</p>

app/views/pages/searched.html.erb
<html>
	<body>
		<section class = "searchscreen">
		<b>You searched for:</b>
		<input name = "search" value = "#" class = "searched">
		</section>
		<br>
		<article>
		<h3>Search Results:</h3>
		<ul>
			<li><%= link_to "", '#', :class => "create round" %></li>
		</ul>
		</article>
	</body>
</html>

app/views/searches/searched.html.erb
<html>
	<body>
		<section class = "searchscreen">
		<b>  You searched for:</b>
		<div class = "searched for"
			<% form_tag students_path do %>
				<% text_field_tag :search, params[:search], :class => "search" %>
			<% end %>
		</div>

		</section>
		<br>
		<article>
		<h3>Search Results:</h3>
		<ul>
			<li><%= link_to "", '#', :class => "create round" %></li>
		</ul>
		</article>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_user.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/new.html.erb
<center><div class = "home">
<div class = "span-8">
	<center><ul>
		<%= form_for @user, :url => logged_in_path do |f| %>
		<li><h1><b>Login</b></h1></li>	
		<li><%= f.text_field :username, :class => "textstyle", :placeholder => "Username" %></li>
		<li><%= f.password_field :password, :class => "textstyle", :placeholder => "Password" %></li>
		<div class="actions">
			<li><%= f.submit "Login"%><li>
		</div>
		<% end %>
	</ul></center>
</div>
<div class= "span-1">
	<center><img src="http://i.imgur.com/ZgEQ3.png"><center>
</div>

<div class = "span-8">
	<center><ul>
		<%= form_for @user do |f| %>
		<li><h1><b>New Account</b></h1></li>	
		<li><%= render 'shared/error_messages_user' %></li>
		<li><%= f.text_field :email, :class => "textstyle", :placeholder => "Email" %></li>
		<li><%= f.text_field :username, :class => "textstyle", :placeholder => "New Username" %></li>
		<li><%= f.password_field :password, :class => "textstyle", :placeholder => "Password" %></li>
		<li><%= f.password_field :password_confirmation, :class => "textstyle", :placeholder => "Confirm Password" %></li>
		<div class="actions">
			<li><%= f.submit "Create"  %><li>
		</div>
		<% end %>
	</ul></center>
</div>
</div></center>

app/views/students/new.html.erb
<center><h1><b>Create New Student<b><h1></center>
<center><div class = "greenbox">
<%= form_for @student do |f| %>
  <%= render 'shared/error_messages' %>
    <%= f.text_field :lastname, :class => "greentext", :placeholder => "Last Name" %>
    <%= f.text_field :firstname, :class => "greentext", :placeholder => "First Name"  %>
    <%= f.text_field :IDnumber, :class => "greentext", :placeholder => "ID number" %>
    <%= f.text_field :graduationyear, :class => "greentext", :placeholder => "Graduation Year" %>
    <%= f.text_field :grade, :class => "greentext", :placeholder => "Grade" %>
    <%= f.text_field :address1, :class => "greentext", :placeholder => "Address 1" %>
    <%= f.text_field :address2, :class => "greentext", :placeholder => "Address 2" %>
    <%= f.text_field :zip, :class => "greentext", :placeholder => "Zip" %>
</div>
  

<div class = "orangebox">
	<br>
<div class ="box">
	<%= f.text_field :email1, :class => "orange", :placeholder => "Email Address 1" %>
    <div class = checkbox>	
	    <%= f.check_box :confirmed1, :class => "checkbox" %><font size= "3">Confirmed</font>
    </div>
    <%= f.text_field :email2, :class => "orange", :placeholder => "Email Address 2" %>
    <div class = checkbox>
	    <%= f.check_box :confirmed2, :class => "checkbox" %><font size= "3">Confirmed</font>
    </div>
</div>
<br>
  
<div class = "box">
	<%= f.text_field :telephone1, :class => "orange", :placeholder => "Telephone Number 1" %>
	<%= f.text_field :telephone2, :class => "orange", :placeholder => "Telephone Number 2"  %>
</div>
  
  <div class="actions">
	  <%= f.submit "Save", :type => :image, :src => "/images/SaveButton.png"%>
  </div>
  <br><br><br>
  <div class="other">
	  <%= link_to "", students_new_path, :class => "newstudent" %>
  </div>
  <br>
  <div class="other">
	  <%= link_to "", logged_in_path, :class => "done" %>
  </div>
</div>
  
</center>
<% end %>

app/views/users/new.html.erb
<<<<<<< HEAD
<div class ="otherhome">
=======
<div class ="retard">
>>>>>>> upstream/master
<div class= "span-1">
	<center><img src="http://i.imgur.com/ZgEQ3.png"><center>
</div>

<div class = "span-8">
	<center><ul>
		<%= form_for @user do |f| %>
		<li><h1><b>New Account</b></h1></li>	
		<li><%= render 'shared/error_messages_user' %></li>
		<li><%= f.text_field :email, :class => "textstyle", :placeholder => "Email" %></li>
		<li><%= f.text_field :username, :class => "textstyle", :placeholder => "New Username" %></li>
		<li><%= f.password_field :password, :class => "textstyle", :placeholder => "Password" %></li>
		<li><%= f.password_field :password_confirmation, :class => "textstyle", :placeholder => "Confirm Password" %></li>
		<div class="actions">
			<li><%= f.submit "Create"  %><li>
		</div>
		<% end %>
	</ul></center>
</div>
<<<<<<< HEAD
=======
</div></center>
>>>>>>> upstream/master
</div>

app/views/users/show.html.erb
<html>
	<body>
		<div class = "body">
			
				
			
			<center><div id = "search_student" class="span-8"><h1>Student Search</h1>
				<div class = "first">
					<ul>
						<div class = "text">
						<form>
								
							<li><input name = "text" name = "first name" placeholder = "First Name" class = "textstyle" ></li>
							<li><input name = "last name" placeholder = "Last Name" class = "textstyle" ></li>
							<li><input name = "id" placeholder = "ID number" class = "textstyle"></li>
							<li><input name = "email" placeholder = "Email" class = "textstyle"></li>
							<li><input name = "telephone" placeholder = "Telephone" class = "textstyle"></li>
							<%= link_to "Search", searched_path, :class => "create round" %>
						</form>
						</div>
					</ul>
				</div>
			</div></center>
			<div class= "span-1">
				<img src="http://i.imgur.com/ZgEQ3.png">
			</div>
			<center><div id = "create_new" class="span-8"><h1>Create New Student</h1>
				<div class = "two">
					<ul>
						<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
						
					</ul>
				</div>
			</div></center>
		</div>
	</body>
</html>
